/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: haerades (https://sketchfab.com/haerades)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/electric-guitar-a998917d451b4b67ad402b1793c7b6c2
Title: Electric Guitar
*/

import { useGLTF } from '@react-three/drei'

export function Guitar(props) {
  const { nodes, materials } = useGLTF('/electric_guitar/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[9.522, -0.885, 0.823]} rotation={[1.499, -1.329, -2.762]} scale={0.38}>
        <group
          position={[-0.806, 1.139, 0.506]}
          rotation={[-1.537, 1.241, -0.028]}
          scale={[157.317, 75.43, 124.959]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Corps_0.geometry}
            material={materials.Noir_plastique}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Corps_1.geometry}
            material={materials.Noir_mtal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Corps_2.geometry}
            material={materials.Blanc}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Corps_3.geometry}
            material={materials.Mtal}
          />
          <group
            position={[-0.651, -0.276, -0.593]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.058, 0.073, 0.103]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['R��glage_Tone_0'].geometry}
              material={materials.Noir_plastique}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['R��glage_Tone_1'].geometry}
              material={materials.Mtal}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['R��glage_Tone_2'].geometry}
              material={materials.Noir_mtal}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Manche002_0.geometry}
            material={materials.Manche}
            position={[2.337, -0.207, 0.042]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-0.512, 1.068, 0.169]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Corde_Mi_Grave_0.geometry}
            material={materials.Mtal}
            position={[1.577, -0.273, -0.081]}
            rotation={[0, -1.548, -Math.PI]}
            scale={[0.002, 0.003, 1.686]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Corde_La_0.geometry}
            material={materials.Mtal}
            position={[1.843, -0.273, -0.04]}
            rotation={[0, -1.548, -Math.PI]}
            scale={[0.002, 0.003, 1.686]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Corde_R��_0'].geometry}
            material={materials.Mtal}
            position={[2.171, -0.273, -0.012]}
            rotation={[0, -1.548, -Math.PI]}
            scale={[0.002, 0.003, 1.686]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Corde_Sol_0.geometry}
            material={materials.Mtal}
            position={[2.224, -0.273, 0.106]}
            rotation={[0, -1.548, -Math.PI]}
            scale={[0.002, 0.003, 1.686]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Corde_Si_0.geometry}
            material={materials.Mtal}
            position={[1.766, -0.271, 0.144]}
            rotation={[0, -1.548, -Math.PI]}
            scale={[0.002, 0.003, 1.686]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Corde_Mi_0.geometry}
            material={materials.Mtal}
            position={[1.08, -0.267, 0.199]}
            rotation={[0, -1.548, -Math.PI]}
            scale={[0.002, 0.003, 1.686]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['R��glages_corde_0'].geometry}
            material={materials.Mtal}
            position={[3.324, -0.28, 0.023]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[-0.014, 0.018, 0.043]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Boutons_0.geometry}
            material={materials.Mtal}
            position={[3.48, -0.198, 0.315]}
            rotation={[-Math.PI, 0, -0.113]}
            scale={[-0.013, 0.027, 0.011]}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/electric_guitar/scene.gltf')
